language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.7.tgz
  - tar xzf mongodb-linux-x86_64-3.4.7.tgz
  - ${PWD}/mongodb-linux-x86_64-3.4.7/bin/mongod --version

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-3.4.7/data
  - ${PWD}/mongodb-linux-x86_64-3.4.7/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-3.4.7/data --logpath ${PWD}/mongodb-linux-x86_64-3.4.7/mongodb.log --fork
  - npm install -g @angular/cli
